export const ERROR_CODE = {
    BAD_REQUEST: 'BAD_REQUEST',
    UNAUTHORIZED: 'UNAUTHORIZED',
    FORBIDDEN: 'FORBIDDEN',
    NOT_FOUND: 'NOT_FOUND',
    CONFLICT: 'CONFLICT',
    INVALID_CREDENTIALS: 'INVALID_CREDENTIALS',
    ACCOUNT_NOT_VERIFIED: 'ACCOUNT_NOT_VERIFIED',
    ACCOUNT_BANNED: 'ACCOUNT_BANNED',
    INTERNAL_SERVER_ERROR: 'INTERNAL_SERVER_ERROR',
    EMAIL_ALREADY_EXISTS: 'EMAIL_ALREADY_EXISTS',
    INVALID_ACCESS_TOKEN: 'INVALID_ACCESS_TOKEN',
    ACCESS_TOKEN_EXPIRED: 'ACCESS_TOKEN_EXPIRED',
    INVALID_REFRESH_TOKEN: 'INVALID_REFRESH_TOKEN',
    REFRESH_TOKEN_REUSED: 'REFRESH_TOKEN_REUSED'
}
